name: lah_project
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  image_picker: ^0.6.7+2
  modal_progress_hud: ^0.1.3
  font_awesome_flutter: ^8.8.1
  flutter_countdown_timer: ^1.4.0
  percent_indicator: ^2.1.1
  google_fonts: ^1.0.0
  expandable: ^4.1.4
  path_provider: ^1.6.18
  cloud_firestore: ^0.13.7
  firebase_storage: ^3.1.6
  fluttertoast: ^4.0.1
  firebase_auth: ^0.16.1
  provider: ^4.1.3
  shared_preferences: ^0.5.12+2
  uuid: ^2.2.2
  file_picker: ^2.0.11
  flutter_datetime_picker: ^1.3.8
  advance_pdf_viewer: ^1.2.0
  quick_feedback: ^0.1.1
  expandable_text: ^1.0.1
  intl: ^0.16.1
  video_player: ^1.0.1
  firebase_core: ^0.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name:

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/documents/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
